version: "3"

services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - data:/usr/share/elasticsearch/data # to persist data
    ports:
      - "9200:9200"

  logstash:
    image: logstash
    command: logstash -f /etc/logstash/logstash.conf
    volumes:
      - ./logs:/var/log/
      - ./config:/etc/logstash

  kibana:
    image: kibana
    ports:
      - "5601:5601"

volumes:
  data:

networks:
  default:
